--- 
artifacts: 
  files: 
    - target/spring-boot-rest-api-playground-h2-0.0.1-SNAPSHOT.jar
phases: 
  build: 
    commands: 
      - "mvn package"
      - "echo \"build stage started\""
  install: 
    pre_build: 
      commands: 
        - "echo \"pre_build stage started\""
    runtime-versions: 
      java: openjdk8
  post_build: 
    commands: 
      - "echo \"post_build stage started\""
version: 0.2
